### Health
GET http://127.0.0.1:8080/-/health

### List users
GET http://127.0.0.1:8080/v1/users

### Get a user
GET http://127.0.0.1:8080/v1/user/4

### Create a user
POST http://127.0.0.1:8080/v1/user/create

### Delete a user
DELETE http://127.0.0.1:8080/v1/user/delete/3
